# Generated by Django 5.0.3 on 2024-03-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_post',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_post',
            field=models.IntegerField(default=5),
        ),
    ]
